### ISSUE TITLE
Add CONTRIBUTING.md + other basic docs 

### ISSUE THREAD

**Issue by amabelleS** [Maakaf/Maakaf-temporary#6]
For new contributors to get oriented and start developing smoothly.
+CODE_OF_CONDUCT.md

**Comment by amabelleS** [comment]
To what fork do I link the contributors? 
``` Fork the project [on GitHub](https://github.com/Maakaf/Maakaf-temporary) ```

For now, I will use this repo, later we need to adjust the links.

**Comment by UrielOfir** [comment]
אפשר לסגור את האישיו הזה?

**Comment by amabelleS** [comment]
כן😊
